from tasks_module.task1_orb_features import *
from tasks_module.task2_sift_features import *
from tasks_module.task3_canny_edges import *
from tasks_module.task5_grayscale import *
from tasks_module.task4_hsv import *
from tasks_module.task6_flip_right import *
from tasks_module.task7_flip_bottom import *
from tasks_module.task8_rotate_45 import *
from tasks_module.task9_rotate_30_point import *
from tasks_module.task10_move_right_10 import *
from tasks_module.task11_change_brightness import *
from tasks_module.task12_change_contrast import *
from tasks_module.task13_gamma_correction import *
from tasks_module.task14_histogram_equalize import *
from tasks_module.task15_white_balance_warm import *
from tasks_module.task16_white_balance_cold import *
from tasks_module.task17_change_palette import *
from tasks_module.task18_binarization import *
from tasks_module.task19_binarization_contours import *
from tasks_module.task20_sobel_contours import *
from tasks_module.task21_blur import *
from tasks_module.task22_fourier_filter_high import *
from tasks_module.task23_fourier_filter_low import *
from tasks_module.task24_erosion import *
from tasks_module.task25_dilation import *
